import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home({ posts }) {
  console.log("postss", posts);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        {/* <meta name="description" content="Generated by create next app" />

        <meta
          property="og:image"
          content={
            "https://bazar-247.s3.us-east-2.amazonaws.com/16144121240101001-94-ah.jpg"
          }
        />
        <meta property="og:image:width" content="400" />
        <meta property="og:image:height" content="300" />

        <meta property="og:type" content="website" />
        <meta property="og:title" content={"title"} />
        <meta property="og:description" content={"desp"} />
        <meta
          property="og:url"
          content={"https://main--pensive-bose-e5a231.netlify.app/"}
        ></meta>

        <meta property="twitter:card" content="summary_large_image" />
        <meta property="twitter:title" content={"title"} />
        <meta
          property="twitter:url"
          content={"https://main--pensive-bose-e5a231.netlify.app/"}
        ></meta>
        <meta property="twitter:description" content={"desp"} />
        <meta
          property="twitter:image"
          content={
            "https://bazar-247.s3.us-east-2.amazonaws.com/16144121240101001-94-ah.jpg"
          }
        />
        <meta name="title" property="og:title" content={"title"} />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {posts.map((item) => (
        <ul>
          <a href={`/dummy/${item.id}`}>{item.productName}</a>
        </ul>
      ))}
    </div>
  );
}
export const getStaticProps = async () => {
  const res = await fetch(
    `https://api-stage.gobazar247.com/v1/products/getAllProducts`
  );
  const posts = await res.json();

  console.log("postss======", posts);

  return { props: { posts: posts.results } };
};
